import type { Metadata } from "next";
import { Jost } from 'next/font/google'
import { Inter } from 'next/font/google'
import "../styles/globals.scss";
import Nav from "@/components/Nav";
import Logo from "@/components/Logo";
import Sidebar from "@/components/Sidebar";
import EffectAmbilight from "@/components/EffectAmbilight";

const fontCommon = Jost({
    subsets: ['latin', 'cyrillic'],
    variable: '--font-common',
    display: 'swap',
})
const fontHeader = Jost({
    subsets: ['latin', 'cyrillic'],
    variable: '--font-header',
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${fontCommon.variable} ${fontHeader.variable}`}>
                <main>
                    <div className='container'>
                        <div className="content-area">
                            <div className="content">
                                {children}
                            </div>
                            <Sidebar />
                        </div>
                    </div>
                </main>
            </body>
        </html>
    );
}
